### ISSUE TITLE
TROCAR O NOME

### ISSUE THREAD

**Issue by LionsWrath** [HackerSpaceMaringa/FutebolRobosArduino#1]
# TROCA O NOME DO ARQUIVO .INO PARA O NOME DA PASTA DO GIT PRA FUNFAR DIREITO NA IDE DO ARDUINO

**Comment by ysiraichi** [comment]
PÁRA DE GRITAR!

**Comment by joao29a** [comment]
ARRUMA LOGA ISSO AE

***LOGO

**Comment by vandersonmr** [comment]
SÉRIO! OLHA A EDUCAÇÃO!
